CREATE TABLE Reports (
    ID BIGINT UNSIGNED AUTO_INCREMENT,
    
    UserID BIGINT UNSIGNED NOT NULL,
    Picture TEXT NOT NULL,
    Description TEXT NOT NULL,
    Location TEXT NOT NULL,
    Action ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    CreatedAt DATETIME NOT NULL DEFAULT NOW(),

    PRIMARY KEY (ID),
    FOREIGN KEY FKReportsUserIDUsersID (UserID) REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8;