CREATE TABLE Notifications (
    ID BIGINT UNSIGNED AUTO_INCREMENT,
    UserID BIGINT UNSIGNED NOT NULL,
    
    Text VARCHAR(255) NOT NULL,
    
    CreatedAt DATETIME NOT NULL DEFAULT NOW(),
    
    PRIMARY KEY (ID),
    FOREIGN KEY FKNotificationsUsers (UserID) REFERENCES Users (ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8;