CREATE TABLE UserVisits (
    UserID BIGINT UNSIGNED NOT NULL,
    AnimalID BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY FKUserVisitsUsers (UserID) REFERENCES Users (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY FKAnimalsUsers (AnimalID) REFERENCES Animals (ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8;