CREATE TABLE CampaignSubmissions (
    UserID BIGINT UNSIGNED NOT NULL,
    CampaignID BIGINT UNSIGNED NOT NULL,
    Submission TEXT NOT NULL,
    Status ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    CreatedAt DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY FKCampaignSubmissionsUsers (UserID) REFERENCES Users (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY FKCampaignSubmissionsCampaigns (CampaignID) REFERENCES Campaigns (ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8;