CREATE TABLE UserVerifications (
    ID BIGINT UNSIGNED AUTO_INCREMENT,

    UserID BIGINT UNSIGNED NOT NULL UNIQUE,
    Token CHAR(32) NOT NULL,
    Succeed BOOLEAN NOT NULL DEFAULT FALSE,

    CreatedAt DATETIME NOT NULL DEFAULT NOW(),

    PRIMARY KEY (ID),
    FOREIGN KEY FKUserVerificationsUsers (UserID) REFERENCES Users (ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8;
