CREATE TABLE Reports (
    ID BIGINT UNSIGNED AUTO_INCREMENT,
    
    Picture TEXT NOT NULL,
    Description TEXT NOT NULL,
    Location TEXT NOT NULL,
    Action ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    CreatedAt DATETIME NOT NULL DEFAULT NOW(),

    PRIMARY KEY (ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8;