CREATE TABLE UserVisits (
    UserID BIGINT UNSIGNED NOT NULL,
    EnclosureID BIGINT UNSIGNED NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY FKUserVisitsUsers (UserID) REFERENCES Users (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY FKEnclosuresUsers (EnclosureID) REFERENCES Enclosures (ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8;