CREATE TABLE Campaigns (
    ID BIGINT UNSIGNED AUTO_INCREMENT,
    
    Picture TEXT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Reward INT NOT NULL,
    
    CreatedAt DATETIME NOT NULL DEFAULT NOW(),
    UpdatedAt DATETIME NOT NULL DEFAULT NOW(),
    
    PRIMARY KEY (ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8;
