@baseURL = http://localhost:8080
@token = v4.public.eyJhdWQiOiIqIiwiZXhwIjoiMjAyNC0wNS0wNFQxMjoxMDoxMSswNzowMCIsImlhdCI6IjIwMjQtMDQtMjdUMTI6MTA6MTErMDc6MDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJuYW1lIjoiT3R0ZXIgV2hvcHBlciIsIm5iZiI6IjIwMjQtMDQtMjdUMTI6MTA6MTErMDc6MDAiLCJzdWIiOiI1In3jqn9t7lKtgLlBDmk-b194NvgZCDwNlnfks4HcuK68eiVBppHYwoGuIBybzXbDX5CHLS5uUPfhfJkn6Xip3AsA
@email = otter.whopper@gmail.com
@password = 12345678

GET {{baseURL}}/api/status
Accept: application/json

### User Sign-up
POST {{baseURL}}/api/users
Content-Type: application/json
    
{
    "email": "{{email}}",
    "password": "{{password}}",
    "passwordConfirmation": "{{password}}",
    "name": "Otter Whopper"
}

### User Log-in
POST {{baseURL}}/api/users/_login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "rememberMe": true
}

### User Fetch Profile
GET {{baseURL}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### GET
GET {{baseURL}}/api
Accept: application/json
Authorization: Bearer {{token}}

### POST
POST {{baseURL}}/api
Content-Type: application/json

{
    "": ""
}

### What is this animal?
POST {{baseURL}}/api/animals/_whatIs
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lat";

-7.2973518381699725
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="long";

112.73693682351974
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="picture"; filename="picture.png"
Content-Type: image/png;

< ./panda.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

